### ISSUE TITLE
How to check if cookie type is required in template

### ISSUE THREAD

**Issue by jannisborgers** [nilsenpaul/craft-complete-cookie-consent#12]
I’m using the example form provided in the README to display a form when YouTube embeds are supposed to be loaded but consent for the `youtube` cookie type is not given.

This renders all cookie types, including the `necessary` option, unchecked and enabled. It has to be:

1. checked
2. disabled

… because obviously users should not be able to disable necessary cookies.

In essence, I need to mirror the cookie banner itself. So this loop in my form:

```
{% for consentType, consentStatus in craft.ccc.consentInfo.consent %}
    <label for="cookieTypes[consentType]">
        <input type="checkbox" name="cookieTypes[]" value="{{ consentType }}"{% if consentStatus == true %} checked{% endif %} /> {{ consentType }}
    </label>
{% endfor %}
```

…would be written like this:

```
{% for consentType, consentStatus, consentRequired in craft.ccc.consentInfo.consent %}
    <label for="cookieTypes[consentType]">
        <input type="checkbox" name="cookieTypes[]" value="{{ consentType }}"{% if consentStatus == true or consentRequired == true %} checked{% endif %}{% if consentRequired %} disabled{% endif %} /> {{ consentType }}
    </label>
{% endfor %}
```

We’d need access to a consentRequired boolean similar to the consentStatus boolean.

**Comment by nilsenpaul** [comment]
@jannisborgers Sorry for the late response. We'll release a new version today, which includes cookie type config in the variable. After that, you can use:

`craft.ccc.consentInfo.cookieTypes` to get an array containing `name`, `defaultOn` and `required`, indexed by the cookie type handle.

**Comment by jannisborgers** [comment]
@nilsenpaul Any news on when 1.0.7 will be released?

**Comment by nilsenpaul** [comment]
@jannisborgers It was, but we forgot to change the version in `composer.json`.
It's available right now, sorry for the delay!
