### ISSUE TITLE
ccc is undefined, null on DOMContentLoaded

### ISSUE THREAD

**Issue by jannisborgers** [nilsenpaul/craft-complete-cookie-consent#13]
I'm trying to only execute Analytics code if consent was submitted and the `analytics` cookie type was checked.

Using the README example, I try to conditionally initialize Google Analytics by adding the following to the head of my main layout template:

```
<script>
if (ccc.consentSubmitted && ccc.consent.statistics) {
    // Analytics initialization
    ga('create', '/* Analytics property */', 'auto');
    ga('set', 'anonymizeIp', true);
    ga('send', 'pageview');
}
</script>
```

This results in `ReferenceError: ccc is not defined`. When I wrap it in an event listener (onload, or DOMContentLoaded), the error changes to `TypeError: ccc is null`.

What am I doing wrong here?

**Comment by nilsenpaul** [comment]
@jannisborgers As of version 1.0.7, the plugin will dispatch a `ccc.loaded` event on the `window` element, so you would be able to do:

```
window.addEventListener('ccc.loaded', function(e) => {
    ga('create', '/* Analytics property */', 'auto');
    ga('set', 'anonymizeIp', true);
    ga('send', 'pageview');
});
```
