### ISSUE TITLE
Banner not showing anymore

### ISSUE THREAD

**Issue by mikewink** [nilsenpaul/craft-complete-cookie-consent#14]
Hello,

first of all, thank you very much for the plugin! We really like the flexibility and options it has.

We have a problem though. We were extensively testing our new website and the CCC banner worked as expected. Now that we changed the server to our live environment the banner is not showing anymore. I can see the html and js in the source code, but nothing is triggered and I don't know how to debug this situation properly. 

Do you have any tips about what to do? Might this be related to the problem with the geolocation issue #9 ? Thank you for any tip.

Best regards
Mike

**Comment by nilsenpaul** [comment]
Hi @mikewink,

- First, check your debug toolbar's cookie panel to see if cookies have already been accepted (you wouldn't be the first ;))
- If that's not it, could you send an email to plugins@nilsenpaul.nl with the production url, so we can have a look at it?

Happy to help, let's make it work!

**Comment by mikewink** [comment]
As the banner now shows up again I'm closing this issue down. I'm still not sure why, but maybe did one of the other plugins or Craft itself have something to do with it. 

Thank you very much for your help and quick support! Great work guys.
