### ISSUE TITLE
Improvement: Hide checkbox for mandatory cookies

### ISSUE THREAD

**Issue by mikewink** [nilsenpaul/craft-complete-cookie-consent#15]
Hello Nils & Paul,

We are using your plugin and it works like a charm for us. Now that cookie policies are getting tougher and tougher we try to adhere as best as we can. One thing we are a bit struggling with is to have a visible checkbox for a mandatory (active and required) cookie setting. 

Our legal team would love to see an option where one would be able to get rid of the checkbox if that kind of cookie is mandatory. We also think it might remove a bit of confusion when people try to uncheck everything, but can't get it to work for the mandatory cookie.

Thank you very much for considering. 

Best regards

Mike

**Comment by nilsenpaul** [comment]
@mikewink Just to be sure ... would that cookie be 'accepted' if the cookie settings are saved? If there would be no checkbox at all, what would be the point of saving the consent for that cookie? Visitors can not consent to something they don't see, right?
