### ISSUE TITLE
Is it possible to retain querystring params in URL when clicking "OK" button in  banner?

### ISSUE THREAD

**Issue by fantasticmachine** [nilsenpaul/craft-complete-cookie-consent#16]
Our site shows a popup when first visited, after the cookie consent banner is displayed/dismissed.

The problem I have is that I now need to prevent that popup showing if users arrive via a URL containing a particular query string param. Easy enough. However clicking the "OK" button in the cookie banner reloads the page without the query string params.

How can I retain those querystring parameters in the URL so I can determine whether or not to show the popup?

**Comment by nilsenpaul** [comment]
Hi Pete, we added the ability to set a redirect URL to be used after form submission. Would that cover your needs?

**Comment by pimago** [comment]
This issue still persists. Are you working on this? For example when a user clicks on an order confirmation email link the querystring with the oder number is removed.
