### ISSUE TITLE
MaxMind URL isn't available anymore

### ISSUE THREAD

**Issue by RickvanBoxtel** [nilsenpaul/craft-complete-cookie-consent#17]
The url you're using for downloading the GeoLite2 DB from MaxMind isn't available anymore:
http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz

See: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

When I set Geolocation method to None, I would expect the banner to show always. But it doesn't, the bannerInfo json gives me: "bannerShouldBeShown":false

So now the cookie message won't show

**Comment by RickvanBoxtel** [comment]
Excuse me, forget about the last part (Geolocation none). 
I see this is already fixed in the last version.

**Comment by nilsenpaul** [comment]
Rick, we fixed this in v1.0.8 by removing support for the MaxMind GeoLite2 DB. Instead, we added support for using the ipstack.com API (key required, free up to 10000 uses per month).

**Comment by RickvanBoxtel** [comment]
Ok great, thanks
