### ISSUE TITLE
Add a “Learn More” button

### ISSUE THREAD

**Issue by romainpoirier** [nilsenpaul/craft-complete-cookie-consent#2]
I would be useful to add a “Learn More” button next to the banner button.

Because, usually, the cookies policy of a website is related to a general privacy policy or a page where the user can learn more about the use of its data.

Also, this could be a link to the page which enable to user to update its preferences, thought a cookie preference form.

I know we can probably use Markdown in the Banner text field, but it would be useful to have something like an Entry field where we could dynamically set this page instead of a URL.

It's probably the missing feature that would allow me to use this plugin in production.

**Comment by nilsenpaul** [comment]
Good one, Romain! We will look into this.

**Comment by nilsenpaul** [comment]
As of v1.0.5, a secondary button is available, with the ability to point this button to an entry or url.
