### ISSUE TITLE
CCC strips parameters from URL after reload

### ISSUE THREAD

**Issue by mikewink** [nilsenpaul/craft-complete-cookie-consent#22]
Hello Nils & Paul,

I have a little problem with your excellent plugin. When we link to our site we add some parameters to those links that we use to optimize the on-boarding process. As most of our visitors are first time visitors they have to consent to cookie usage. Once they do, the site reloads and the parameters are stripped. 

I'm running Craft 3.4.11 Pro with CCC 1.0.8.3.

Could you please change the code so it keeps the parameters after the reload? Or is there a setting I miss? 

Thank you very much.

PS: One off topic question. Is CCC multi-site compatible?

**Comment by mikewink** [comment]
I see that the actionSubmit method in the ConsentController is responsible for the redirect.

I "hacked" the following change into my code and it works.

Old:
```
return $this->redirectToPostedUrl();
```

New:
```
return $this->redirect($request->getAbsoluteUrl());
```

I am not sure if you need to use the other method, or if there is a way to alter the redirect URL in the actionSubmit method and keep the return as is.

**Comment by nilsenpaul** [comment]
@mikewink We'll look into this asap!

**Comment by nilsenpaul** [comment]
About your off topic question: yes, CCC is multi-site compatible.

**Comment by davydepauw** [comment]
@nilsenpaul Have you got the chance to look into this? This still seems to be an issue. Or is there another way to solve this? 
This is troublesome for tracking UTM tags. These get lost during consent redirect and therefore don't show up in Analytics.
