### ISSUE TITLE
W3C markup validation error

### ISSUE THREAD

**Issue by romainpoirier** [nilsenpaul/craft-complete-cookie-consent#3]
The plugin adds an unwanted markup validation error:

`Error: Element cookiebanner not allowed as child of element div in this context. (Suppressing further errors from this subtree.)`

Because of this empty tag injected:
`<cookiebanner></cookiebanner>`

**Comment by nilsenpaul** [comment]
Right now, this is because of the way Vue works. We will look into making this W3C compliant.

**Comment by nilsenpaul** [comment]
I should have read the Vue docs ;)
As of v1.0.5.1, the custom tag contains a hyphen, making it [W3C compliant](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name).
If you have any static caching going on, be sure to clear your caches.
