### ISSUE TITLE
Disable cookie consent for certain templates

### ISSUE THREAD

**Issue by WHITE-developer** [nilsenpaul/craft-complete-cookie-consent#32]
At this moment each template loads the cookie consent bar. 

Now we have a certain template where we don't want the plugin to load, is this possible?

**Comment by nilsenpaul** [comment]
We've just added a config field to add URLs to ignore:

<img width="438" alt="Schermafbeelding 2021-09-13 om 16 19 42" src="https://user-images.githubusercontent.com/6794819/133100550-099d4c4a-8cd8-42f7-8200-e15d2ce567c9.png">

This example would prevent Complete Cookie Consent from being loaded on all URLs that start with "/blog".

Would this help in your specific use case?

**Comment by WHITE-developer** [comment]
Haven't tested it yet, this certainly should do the job. Thanks!

**Comment by WHITE-developer** [comment]
Getting an error when leaving the table empty
`count(): Parameter must be an array or an object that implements Countable`
 in /var/www/html/vendor/nilsenpaul/complete-cookie-consent/src/Plugin.php at line 99

**Comment by nilsenpaul** [comment]
Did you upgrade to the latest version, yet? Should be fixed.

**Comment by WHITE-developer** [comment]
1.0.9.3, yep

**Comment by nilsenpaul** [comment]
1.0.9.4 should be available within minutes, should really be fixed, this time ;)

**Comment by WHITE-developer** [comment]
Yes, perfect :+1:
