### ISSUE TITLE
[Craft 4] Unable to add/reorder/delete table rows

### ISSUE THREAD

**Issue by WHITE-developer** [nilsenpaul/craft-complete-cookie-consent#40]
Since Craft 4 the defaults for editable tables changed. https://github.com/craftcms/cms/commit/1b197ef7c6425f59544b9097f8339beeea9de771
allowAdd, allowReorder and allowDelete are now default false, so should be added here https://github.com/nilsenpaul/craft-complete-cookie-consent/blob/master/src/templates/settings.html#L82

**Comment by nilsenpaul** [comment]
Added this in v1.1.1, please upgrade.
