### ISSUE TITLE
Rename plugin in CP

### ISSUE THREAD

**Issue by mikewink** [nilsenpaul/craft-complete-cookie-consent#5]
Please let us rename the plugin name in the control panel. It's currently way too long and does not even fit in the control panel left sidebar. Other plugins allow renaming their plugins and it's an excellent option to adjust wording. 

If it's not an option, could you please make a shorter name instead? Thank you.

Thank you.

**Comment by nilsenpaul** [comment]
@mikewink, as of v1.0.5.2, this is possible.
