### ISSUE TITLE
Amend markup to allow for more flexible styling options

### ISSUE THREAD

**Issue by Kashkin** [nilsenpaul/craft-complete-cookie-consent#6]
Hi!

I'm currently evaluating this plugin to see if it's suitable for a project.

For the most part, if seems like a perfect fit and it's clear you've put a lot of thought into it.

I think it's great for an out-of-the box, no-coding-required solution, but could be improved to allow for more custom layouts.

I've added some new containers with more classes to allow for easier styling, and would allow for custom CSS that positions elements using flexbox or grid. It also caters for checkbox replacement techniques, with a `<span>` following the `<input>`. I've also opted for a `<button>` element for the submit, as this is a more modern approach.

I've deleted some of the code (hidden inputs) that wasn't relevant to the new classes.

Please let me know your thoughts on adjusting the markup.

```html
<div id="ccc">
  <div class="ccc-banner ccc-banner--bottom">
    <div class="ccc-banner__text">
      <h3 class="ccc-banner__title">This website uses cookies</h3>
      <p class="ccc-banner__description">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis, reiciendis.
      </p>
    </div>
    <form class="ccc-banner__form ccc-form" method="POST">
      <div class="ccc-form__inner">
        <label class="ccc-form__label" for="cookieType-necessary">
          <input type="hidden" name="cookieTypes[]" value="necessary" />
          <input
            class="ccc-form__input"
            id="cookieType-necessary"
            type="checkbox"
            name="cookieTypes[]"
            disabled="disabled"
            value="necessary"
          />
          <span class="ccc-form__label-text">Necessary</span>
        </label>
      </div>
      <div class="ccc-banner__buttons">
        <button type="submit" class="ccc-banner__button ccc-banner__button--primary">Accept</button>
        <a href="#" class="ccc-banner__button ccc-banner__button--secondary">Learn more</a>
      </div>
    </form>
  </div>
</div>
```

**Comment by nilsenpaul** [comment]
@Kashkin, thanks for your uplifting words!
I think we could easily add this to the plugin, we'll put it on the board!
